-- STEP 1: Run this FIRST in Supabase SQL Editor
-- Adds auto-increment defaults to all id columns

DO $$
BEGIN

  -- Try sequence approach first (tables created with SERIAL already have sequences)
  BEGIN
    ALTER TABLE sims        ALTER COLUMN id SET DEFAULT nextval('sims_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE sims        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE devices     ALTER COLUMN id SET DEFAULT nextval('devices_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE devices     ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE fuel_sensors ALTER COLUMN id SET DEFAULT nextval('fuel_sensors_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE fuel_sensors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE installations ALTER COLUMN id SET DEFAULT nextval('installations_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE installations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE paired_bundles ALTER COLUMN id SET DEFAULT nextval('paired_bundles_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE paired_bundles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE rtd_bundles ALTER COLUMN id SET DEFAULT nextval('rtd_bundles_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE rtd_bundles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE damage_events ALTER COLUMN id SET DEFAULT nextval('damage_events_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE damage_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

  BEGIN
    ALTER TABLE movements ALTER COLUMN id SET DEFAULT nextval('movements_id_seq'::regclass);
  EXCEPTION WHEN undefined_object THEN
    ALTER TABLE movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END;

END $$;

-- Verify
SELECT table_name, column_name, column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND column_name = 'id'
  AND table_name IN ('sims','devices','fuel_sensors','installations','paired_bundles','rtd_bundles','damage_events','movements')
ORDER BY table_name;
